version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test
    ports:
      - "5000:5000"
  nginx:
    image: candylandbare/4132202-3-64-lab3:lastes
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysqlcp